CREATE PROCEDURE ListarEmpleados

	AS
	BEGIN
		SET NOCOUNT ON;
		BEGIN TRY
			SELECT Nombre,IdPuesto FROM Empleado WHERE Activo=1 ORDER BY Nombre
		END TRY
		BEGIN CATCH
			INSERT INTO DBErrores VALUES (
			SUSER_SNAME(),
			ERROR_NUMBER(),
			ERROR_STATE(),
			ERROR_SEVERITY(),
			ERROR_LINE(),
			ERROR_PROCEDURE(),
			ERROR_MESSAGE(),
			GETDATE()
			)
		END CATCH
		SET NOCOUNT OFF;
	END

--EXECUTE ListarEmpleados